import { Permission, UserRole } from '../types';

export interface SearchAction {
  id: string;
  label: string;
  path: string;
  description: string;
  category: string;
  keywords?: string[];
  requiredPermissions?: Permission[];
  roles?: UserRole[];
  excludedRoles?: UserRole[];
}

// Note: requiredPermissions acts as an "any of" check. As long as the user has
// one of the listed permissions, the action will be available in search.
export const SEARCHABLE_ACTIONS: SearchAction[] = [
  {
    id: 'dashboard',
    label: 'Dashboard Overview',
    path: '/dashboard',
    description: 'Company KPIs, reminders, and quick stats',
    category: 'Overview',
    keywords: ['home', 'overview', 'landing'],
  },
  {
    id: 'reports',
    label: 'Reports Hub',
    path: '/reports',
    description: 'Performance, finance, and HR reporting',
    category: 'Overview',
    keywords: ['analytics', 'insights'],
    requiredPermissions: [Permission.VIEW_REPORTS, Permission.VIEW_REPORTS_PERFORMANCE],
  },
  {
    id: 'reports-profit-loss',
    label: 'Profit & Loss Report',
    path: '/reports/profit-loss',
    description: 'Income statement with trading income and COGS',
    category: 'Sales & Finance',
    keywords: ['p&l', 'income statement', 'profit loss'],
    requiredPermissions: [Permission.VIEW_FINANCIAL_REPORTS],
  },
  {
    id: 'reports-balance-sheet',
    label: 'Balance Sheet',
    path: '/reports/balance-sheet',
    description: 'Statement of financial position and equity roll-forward',
    category: 'Sales & Finance',
    keywords: ['balance sheet', 'statement of financial position', 'equity'],
    requiredPermissions: [Permission.VIEW_FINANCIAL_REPORTS],
  },
  {
    id: 'leads',
    label: 'Leads Pipeline',
    path: '/leads',
    description: 'Kanban board for prospects and follow-ups',
    category: 'CRM',
    keywords: ['crm', 'prospects', 'pipeline'],
    requiredPermissions: [Permission.VIEW_LEADS, Permission.VIEW_ALL_LEADS],
  },
  {
    id: 'clients',
    label: 'Clients & Businesses',
    path: '/clients',
    description: 'Client records, businesses, and balances',
    category: 'CRM',
    keywords: ['accounts', 'customers'],
    requiredPermissions: [Permission.VIEW_CLIENTS_BUSINESSES, Permission.VIEW_ALL_CLIENTS_BUSINESSES],
  },
  {
    id: 'services',
    label: 'Service Catalog',
    path: '/services',
    description: 'Manage services, packages, and rates',
    category: 'Services',
    keywords: ['offerings', 'catalog'],
    requiredPermissions: [Permission.VIEW_SERVICES, Permission.MANAGE_SERVICES],
  },
  {
    id: 'promotions',
    label: 'Promotions',
    path: '/promotions',
    description: 'Configure sales promotions and bundles',
    category: 'Services',
    keywords: ['discounts', 'offers'],
    requiredPermissions: [Permission.MANAGE_PROMOTIONS],
  },
  {
    id: 'sales',
    label: 'Sales Records',
    path: '/sales',
    description: 'Track deals across services and teams',
    category: 'Sales & Finance',
    keywords: ['deals', 'records'],
    requiredPermissions: [Permission.VIEW_SALES_RECORDS, Permission.VIEW_ALL_SALES_RECORDS],
  },
  {
    id: 'facebook-ads',
    label: 'Facebook Ads Workspace',
    path: '/facebook-ads/dashboard',
    description: 'Campaigns, spend, and settings',
    category: 'Sales & Finance',
    keywords: ['ads', 'facebook', 'campaigns'],
    requiredPermissions: [Permission.MANAGE_FACEBOOK_ADS],
  },
  {
    id: 'finance-documents',
    label: 'Financial Documents',
    path: '/finance/documents',
    description: 'Quotations, invoices, and receipts',
    category: 'Sales & Finance',
    keywords: ['invoices', 'quotations', 'finance'],
    requiredPermissions: [
      Permission.MANAGE_PAYMENTS_RECEIPTS,
      Permission.MANAGE_QUOTATIONS,
      Permission.MANAGE_INVOICES,
    ],
  },
  {
    id: 'finance-clients-to-pay',
    label: 'Pending Payments',
    path: '/finance/clients-to-pay',
    description: 'Clients with outstanding balances',
    category: 'Sales & Finance',
    keywords: ['collections', 'receivables'],
    requiredPermissions: [Permission.VIEW_CLIENTS_TO_PAY],
  },
  {
    id: 'finance-visa',
    label: 'Visa Card Management',
    path: '/finance/visa-cards',
    description: 'Company Visa cards and reload history',
    category: 'Sales & Finance',
    keywords: ['cards', 'reloads'],
    requiredPermissions: [Permission.MANAGE_VISA_CARDS],
  },
  {
    id: 'finance-expenses',
    label: 'Expense Tracking',
    path: '/finance/expenses',
    description: 'Record and review company expenses',
    category: 'Sales & Finance',
    keywords: ['expenses', 'spend'],
    requiredPermissions: [Permission.MANAGE_EXPENSES],
  },
  {
    id: 'finance-ap',
    label: 'Accounts Payable',
    path: '/finance/ap',
    description: 'Vendors, invoices, and payment runs',
    category: 'Sales & Finance',
    keywords: ['ap', 'vendors'],
    requiredPermissions: [Permission.MANAGE_ACCOUNTS_PAYABLE],
  },
  {
    id: 'finance-credit-notes',
    label: 'Credit Notes',
    path: '/finance/credit-notes',
    description: 'Sales adjustments and credit notes',
    category: 'Sales & Finance',
    keywords: ['credit note', 'credit notes', 'adjustments', 'credit'],
    requiredPermissions: [Permission.MANAGE_ACCOUNTS_PAYABLE],
  },
  {
    id: 'finance-ar',
    label: 'Accounts Receivable',
    path: '/finance/ar',
    description: 'Customer invoicing and receipts',
    category: 'Sales & Finance',
    keywords: ['ar', 'customers'],
    requiredPermissions: [Permission.MANAGE_ACCOUNTS_RECEIVABLE],
  },
  {
    id: 'finance-cash',
    label: 'Cash & Treasury',
    path: '/finance/cash',
    description: 'Bank accounts, cash flow, reconciliations',
    category: 'Sales & Finance',
    keywords: ['cash', 'treasury', 'bank'],
    requiredPermissions: [Permission.MANAGE_TREASURY],
  },
  {
    id: 'finance-fixed-assets',
    label: 'Fixed Assets',
    path: '/finance/fixed-assets',
    description: 'Asset register, depreciation, disposals',
    category: 'Sales & Finance',
    keywords: ['assets', 'depreciation'],
    requiredPermissions: [Permission.MANAGE_FIXED_ASSETS],
  },
  {
    id: 'finance-capital',
    label: 'Capital Management',
    path: '/finance/capital',
    description: 'Equity and debt tracking',
    category: 'Sales & Finance',
    keywords: ['loans', 'equity'],
    requiredPermissions: [Permission.MANAGE_CAPITAL],
  },
  {
    id: 'finance-analytics',
    label: 'Financial Analytics',
    path: '/finance/analytics',
    description: 'Income statement, balance sheet, budgets',
    category: 'Sales & Finance',
    keywords: ['reports', 'analysis'],
    requiredPermissions: [Permission.VIEW_FINANCIAL_REPORTS],
  },
  {
    id: 'projects',
    label: 'Projects Portfolio',
    path: '/projects',
    description: 'Project status, teams, and linked sales',
    category: 'Projects & Tasks',
    keywords: ['projects', 'delivery'],
    requiredPermissions: [Permission.VIEW_PROJECTS, Permission.VIEW_ALL_PROJECTS],
  },
  {
    id: 'tasks',
    label: 'Task Management',
    path: '/tasks',
    description: 'Kanban and list views for work items',
    category: 'Projects & Tasks',
    keywords: ['tasks', 'todos'],
    requiredPermissions: [Permission.VIEW_TASKS, Permission.VIEW_ALL_TASKS],
  },
  {
    id: 'surveys',
    label: 'Surveys & Forms',
    path: '/surveys',
    description: 'Collect and review survey responses',
    category: 'Projects & Tasks',
    keywords: ['forms', 'quizzes'],
    requiredPermissions: [Permission.MANAGE_SURVEYS],
  },
  {
    id: 'my-profile',
    label: 'My Profile',
    path: '/profile',
    description: 'Personal details and preferences',
    category: 'My Space',
    keywords: ['account', 'profile'],
    requiredPermissions: [Permission.VIEW_OWN_PROFILE],
  },
  {
    id: 'my-tasks',
    label: 'My Tasks',
    path: '/my-tasks',
    description: 'Tasks assigned to me',
    category: 'My Space',
    keywords: ['self', 'todos'],
    requiredPermissions: [Permission.VIEW_TASKS],
  },
  {
    id: 'my-leave',
    label: 'My Leave',
    path: '/my/leave',
    description: 'Request and monitor personal leave',
    category: 'My Space',
    keywords: ['absence', 'leave'],
    requiredPermissions: [Permission.VIEW_OWN_LEAVE_REQUESTS],
  },
  {
    id: 'my-payroll',
    label: 'My Payroll',
    path: '/my-payroll',
    description: 'Payslips, allowances, and history',
    category: 'My Space',
    keywords: ['salary', 'pay'],
    requiredPermissions: [Permission.VIEW_OWN_PAYSLIP],
  },
  {
    id: 'my-kpi',
    label: 'My KPIs',
    path: '/my/kpi',
    description: 'Assigned goals and evaluation forms',
    category: 'My Space',
    keywords: ['performance', 'targets'],
  },
  {
    id: 'notifications',
    label: 'Update Notifications',
    path: '/my-notifications',
    description: 'System alerts you have received',
    category: 'My Space',
    keywords: ['alerts', 'messages'],
  },
  {
    id: 'hr-staff',
    label: 'Staff Management',
    path: '/hr/staff',
    description: 'Employee directory and profiles',
    category: 'HR',
    keywords: ['employees', 'directory'],
    requiredPermissions: [Permission.VIEW_STAFF_LIST],
  },
  {
    id: 'hr-payroll',
    label: 'Payroll Admin',
    path: '/hr/payroll',
    description: 'Payroll runs, approvals, and payouts',
    category: 'HR',
    keywords: ['payroll', 'salary'],
    requiredPermissions: [Permission.VIEW_PAYROLL_ADMIN],
  },
  {
    id: 'hr-leave-admin',
    label: 'Leave Admin',
    path: '/hr/leave-admin',
    description: 'Approve or decline leave requests',
    category: 'HR',
    keywords: ['leave', 'approvals'],
    requiredPermissions: [Permission.VIEW_LEAVE_ADMIN],
  },
  {
    id: 'hr-holidays',
    label: 'Holiday Calendar',
    path: '/hr/holidays',
    description: 'Company-wide holidays and closures',
    category: 'HR',
    keywords: ['holidays', 'calendar'],
    requiredPermissions: [Permission.MANAGE_HOLIDAYS],
  },
  {
    id: 'hr-attendance',
    label: 'Attendance Admin',
    path: '/hr/attendance',
    description: 'Import or adjust attendance records, configure attendance rules',
    category: 'HR',
    keywords: ['attendance', 'timesheet', 'rules', 'settings', 'policy', 'office hours', 'late', 'leave'],
    requiredPermissions: [Permission.MANAGE_ATTENDANCE],
  },
  {
    id: 'hr-activity-log',
    label: 'Activity Log',
    path: '/hr/activity-log',
    description: 'Centralized audit trail for the last 60 days',
    category: 'HR',
    keywords: ['audit', 'log', 'history'],
    requiredPermissions: [Permission.VIEW_ACTIVITY_LOG],
  },
  {
    id: 'hr-kpi-management',
    label: 'KPI Library',
    path: '/hr/kpi-management',
    description: 'Create and assign KPIs',
    category: 'HR',
    keywords: ['kpi', 'performance'],
    requiredPermissions: [Permission.MANAGE_KPI_LIBRARY],
  },
  {
    id: 'hr-team-kpi',
    label: 'Team KPI Sheets',
    path: '/hr/team-kpis',
    description: 'Review team KPI progress',
    category: 'HR',
    keywords: ['team', 'performance'],
    requiredPermissions: [Permission.VIEW_TEAM_KPIS],
  },
  {
    id: 'sms-compose',
    label: 'SMS Compose',
    path: '/sms/compose',
    description: 'Send SMS blasts and campaigns',
    category: 'SMS',
    keywords: ['sms', 'message', 'campaign'],
    requiredPermissions: [Permission.SEND_SMS],
  },
  {
    id: 'sms-outbox',
    label: 'SMS Outbox',
    path: '/sms/outbox',
    description: 'Track delivery status of batches',
    category: 'SMS',
    keywords: ['sms', 'status'],
    requiredPermissions: [Permission.VIEW_SMS_MODULE],
  },
  {
    id: 'sms-templates',
    label: 'SMS Templates',
    path: '/sms/templates',
    description: 'Manage reusable SMS content',
    category: 'SMS',
    keywords: ['templates', 'sms'],
    requiredPermissions: [Permission.MANAGE_SMS_TEMPLATES],
  },
  {
    id: 'sms-settings',
    label: 'SMS Settings',
    path: '/sms/settings',
    description: 'Providers, sender IDs, and API keys',
    category: 'SMS',
    keywords: ['settings', 'sms'],
    requiredPermissions: [Permission.MANAGE_SMS_SETTINGS],
  },
  {
    id: 'settings',
    label: 'System Settings',
    path: '/settings',
    description: 'Company profile, lists, and permissions',
    category: 'System',
    keywords: ['settings', 'configuration'],
    requiredPermissions: [Permission.MANAGE_SETTINGS],
  },
];

