import React from 'react';
import { FacebookAdsSaleRecord, CompanyProfileSetting, Client, Business } from '../../types';

interface FacebookAdsPDFTemplateProps {
  campaigns: FacebookAdsSaleRecord[];
  companyProfile: CompanyProfileSetting | null;
  clientOrBusiness: Client | Business | null;
  dateRange: { start: string, end: string };
}

const FacebookAdsPDFTemplate: React.FC<FacebookAdsPDFTemplateProps> = ({ campaigns, companyProfile, clientOrBusiness, dateRange }) => {
  const formatDate = (dateString: string) => new Date(dateString).toLocaleDateString('en-GB');

  const pageStyle: React.CSSProperties = {
    fontFamily: '"Inter", "Helvetica Neue", "Arial", sans-serif',
    color: '#1f2937', // Gray-800
    backgroundColor: '#fff',
    width: '210mm',
    minHeight: '297mm',
    padding: '1in',
    boxSizing: 'border-box',
  };

  return (
    <div style={pageStyle}>
      <header style={{ textAlign: 'center', borderBottom: '2px solid #3B82F6', paddingBottom: '15px', marginBottom: '30px' }}>
        {companyProfile?.logoUrl && (
          <img 
            src={companyProfile.logoUrl} 
            alt="Company Logo" 
            style={{ 
              maxHeight: '70px', 
              maxWidth: '200px',
              marginBottom: '15px',
              display: 'block',
              marginLeft: 'auto',
              marginRight: 'auto',
              objectFit: 'contain'
            }}
            crossOrigin="anonymous"
          />
        )}
        <h1 style={{ fontSize: '24px', margin: 0, fontWeight: 'bold' }}>{companyProfile?.companyName || 'Company'}</h1>
        <h2 style={{ fontSize: '20px', margin: '5px 0', color: '#3B82F6' }}>Facebook Ads Campaign Report</h2>
      </header>

      <div style={{ marginBottom: '25px', fontSize: '12px' }}>
        <p><strong>Report For:</strong> {clientOrBusiness?.name}</p>
        <p><strong>Date Range:</strong> {formatDate(dateRange.start)} - {formatDate(dateRange.end)}</p>
      </div>

      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '10px' }}>
        <thead>
          <tr style={{ backgroundColor: '#eff6ff' }}>
            <th style={{ border: '1px solid #d1d5db', padding: '10px', textAlign: 'left' }}>Campaign Name</th>
            <th style={{ border: '1px solid #d1d5db', padding: '10px', textAlign: 'left' }}>Status</th>
            <th style={{ border: '1px solid #d1d5db', padding: '10px', textAlign: 'right' }}>Budget (USD)</th>
            <th style={{ border: '1px solid #d1d5db', padding: '10px', textAlign: 'right' }}>Actual Spend (USD)</th>
            <th style={{ border: '1px solid #d1d5db', padding: '10px', textAlign: 'right' }}>Impressions</th>
            <th style={{ border: '1px solid #d1d5db', padding: '10px', textAlign: 'right' }}>Clicks</th>
            <th style={{ border: '1px solid #d1d5db', padding: '10px', textAlign: 'right' }}>Billed (MMK)</th>
          </tr>
        </thead>
        <tbody>
          {campaigns.map(ad => (
            <tr key={ad.id}>
              <td style={{ border: '1px solid #d1d5db', padding: '8px' }}>{ad.campaignName}</td>
              <td style={{ border: '1px solid #d1d5db', padding: '8px' }}>{ad.campaignStatus}</td>
              <td style={{ border: '1px solid #d1d5db', padding: '8px', textAlign: 'right' }}>{ad.budgetUSD.toLocaleString()}</td>
              <td style={{ border: '1px solid #d1d5db', padding: '8px', textAlign: 'right' }}>{ad.actualSpendUSD?.toLocaleString() || '-'}</td>
              <td style={{ border: '1px solid #d1d5db', padding: '8px', textAlign: 'right' }}>{ad.impressions?.toLocaleString() || '-'}</td>
              <td style={{ border: '1px solid #d1d5db', padding: '8px', textAlign: 'right' }}>{ad.clicks?.toLocaleString() || '-'}</td>
              <td style={{ border: '1px solid #d1d5db', padding: '8px', textAlign: 'right', fontWeight: 'bold' }}>{ad.grandTotalMMK.toLocaleString()}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <footer style={{ marginTop: '40px', paddingTop: '15px', borderTop: '1px solid #ccc', textAlign: 'center', fontSize: '9px', color: '#6b7281' }}>
        <p>This report was generated by {companyProfile?.appName || 'ERP System'}.</p>
      </footer>
    </div>
  );
};

export default FacebookAdsPDFTemplate;
